In [71]:
import numpy as np

In [72]:
a=np.array(4)
a

array(4)

1D Array (One-Dimensional Array):


Represents a single row of elements (like a list in Python).


In [73]:
a=np.array([10,20,40])
print(a)

[10 20 40]


2D Array (Two-Dimensional Array):

Represents a table or grid (rows and columns).


In [74]:
a=np.array([[10,20],[3,7]])
print(a)

[[10 20]
 [ 3  7]]


In [75]:
a[1][1]

np.int64(7)

3D Array (Three-Dimensional Array):

Represents multiple 2D arrays stacked together.

Think of it as a cube or a stack of matrices

In [76]:
c=np.array([[[1,2,],[4,5]],[[7,8],[11,23]]])
print(c)

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [11 23]]]


In [77]:
c[0][1][1]

np.int64(5)

In [ ]:
import numpy as np

# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6],[1,1]])


print(A + B)

print(A - B)

print(A * B)

print(A / B)

print(A.dot(B))


[[6 8]
 [4 5]]
[[-4 -4]
 [ 2  3]]
[[ 5 12]
 [ 3  4]]
[[0.2        0.33333333]
 [3.         4.        ]]
[[ 7  8]
 [19 22]]


In [6]:
# Creating a 2D array
matrix = np.array([[1, 2], [3, 4]])

# Matrix operations
print("Matrix:\n", matrix)
print("Transpose:\n", np.transpose(matrix))
print("Dot Product:\n",np.dot(matrix,matrix))



Matrix:
 [[1 2]
 [3 4]]
Transpose:
 [[1 3]
 [2 4]]
Dot Product:
 [[ 7 10]
 [15 22]]
