In [122]:
import numpy as np

In [123]:
list=[1,2,3]
arr=np.array(list)
arr

array([1, 2, 3])

In [153]:
print(arr.size)
print(arr.shape)
print(arr*2)
print(arr/10)
print(arr.ndim )
print(type(arr))


10
(10,)
[ 8  2  8  8  8 16  8 12  4  4]
[0.4 0.1 0.4 0.4 0.4 0.8 0.4 0.6 0.2 0.2]
1
<class 'numpy.ndarray'>


In [131]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [155]:
print(np.zeros((2,2)))
print(np.ones((2,3)))

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [156]:
print(np.linspace(0,10,5))
print(np.linspace(0,5,10))

[ 0.   2.5  5.   7.5 10. ]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [158]:
np.random.randint(0,10)

3

In [138]:
arr=np.random.randint(1,10,5)
arr



array([7, 2, 2, 1, 8], dtype=int32)

In [139]:
arr.max()

np.int32(8)

In [140]:
np.random.randint(0,10,(3,4))

array([[9, 8, 9, 3],
       [6, 5, 4, 8],
       [6, 5, 0, 1]], dtype=int32)

In [141]:
np.random.randint(0,10,(4,4))

array([[4, 6, 5, 8],
       [6, 3, 0, 5],
       [7, 2, 8, 5],
       [7, 2, 6, 1]], dtype=int32)

In [142]:
arr=np.random.randint(1,10,10)
arr

array([4, 1, 4, 4, 4, 8, 4, 6, 2, 2], dtype=int32)

In [143]:
mat=np.arange(9)
mat

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [144]:
mat.reshape((3,3))


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [145]:
mat.max()

np.int64(8)

In [146]:
mat.min()

np.int64(0)

In [147]:
mat.sum()

np.int64(36)

In [148]:
a=np.random.randint(0,9,(3,3))
b=np.random.randint(11,20,(3,3))

a

array([[8, 3, 1],
       [8, 8, 4],
       [6, 0, 6]], dtype=int32)

In [149]:
b

array([[15, 16, 17],
       [16, 14, 15],
       [12, 18, 11]], dtype=int32)

In [150]:
a+b

array([[23, 19, 18],
       [24, 22, 19],
       [18, 18, 17]], dtype=int32)

In [151]:
# Creating a 2D array
matrix = np.array([[1, 2], [3, 4]])

# Matrix operations
print("Matrix:\n", matrix)
print("Transpose:\n", np.transpose(matrix))
print("Dot Product:\n", np.dot(matrix, matrix))


Matrix:
 [[1 2]
 [3 4]]
Transpose:
 [[1 3]
 [2 4]]
Dot Product:
 [[ 7 10]
 [15 22]]
